// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace MasterTPSApp.Server.Migrations
{
    [DbContext(typeof(AppDbContext))]
    [Migration("20240730102958_UpdatePlaceIdToIdentity")]
    partial class UpdatePlaceIdToIdentity
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.7")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("Person", b =>
                {
                    b.Property<long>("Id")
                        .HasColumnType("bigint");

                    b.Property<DateTime>("BirthDate")
                        .HasColumnType("datetime2");

                    b.Property<long>("Height")
                        .HasColumnType("bigint");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(33)
                        .HasColumnType("nvarchar(33)");

                    b.Property<string>("PersonalIdNumber")
                        .IsRequired()
                        .HasMaxLength(13)
                        .HasColumnType("nvarchar(13)");

                    b.Property<long>("PlaceOfBirthId")
                        .HasColumnType("bigint");

                    b.Property<long?>("PlaceOfResidenceId")
                        .HasColumnType("bigint");

                    b.Property<string>("Surname")
                        .IsRequired()
                        .HasMaxLength(33)
                        .HasColumnType("nvarchar(33)");

                    b.HasKey("Id");

                    b.HasIndex("PlaceOfBirthId");

                    b.HasIndex("PlaceOfResidenceId");

                    b.ToTable("Persons");
                });

            modelBuilder.Entity("Place", b =>
                {
                    b.Property<long>("Id")
                        .HasColumnType("bigint");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(40)
                        .HasColumnType("nvarchar(40)");

                    b.Property<int>("Population")
                        .HasColumnType("int");

                    b.Property<int>("PostalCode")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.ToTable("Places");
                });

            modelBuilder.Entity("Person", b =>
                {
                    b.HasOne("Place", "PlaceOfBirth")
                        .WithMany("PeopleBornHere")
                        .HasForeignKey("PlaceOfBirthId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("Place", "PlaceOfResidence")
                        .WithMany("PeopleLivingHere")
                        .HasForeignKey("PlaceOfResidenceId")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.Navigation("PlaceOfBirth");

                    b.Navigation("PlaceOfResidence");
                });

            modelBuilder.Entity("Place", b =>
                {
                    b.Navigation("PeopleBornHere");

                    b.Navigation("PeopleLivingHere");
                });
#pragma warning restore 612, 618
        }
    }
}
